version: "3.8"

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
