logging:
  level:
    root: INFO
    skillmanagement: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

metrics:
  employees:
    total:
      update:
        rate: "PT1M"
        delay: "PT10S"
  projects:
    total:
      update:
        rate: "PT1M"
        delay: "PT10S"
  skills:
    total:
      update:
        rate: "PT1M"
        delay: "PT10S"
